### ISSUE TITLE
serialize_always attribute mysteriously fails on array fields

### ISSUE THREAD

**Issue by detly** [jonasbb/serde_with#335]
The following runs fine:

```rust
#[serde_with::skip_serializing_none]
#[derive(serde::Serialize, serde::Deserialize)]
struct Huh {
    one: Option<String>,

   #[serialize_always]
    two: Option<String>,
}

fn main() {
    let thing = Huh { one: None, two: None };
    println!("{}", serde_json::to_string_pretty(&thing).unwrap());
}
```

Output is:

```text
{
  "two": null
}
```

However, turning `two` into an array makes it fail to compile:

```rust
#[serde_with::skip_serializing_none]
#[derive(serde::Serialize, serde::Deserialize)]
struct Huh {
    one: Option<String>,

    #[serialize_always]
    two: [Option<String>; 1],
}

fn main() {
    let thing = Huh { one: None, two: [None] };
    println!("{}", serde_json::to_string_pretty(&thing).unwrap());
}
```

Compiler output:

```text
error: cannot find attribute `serialize_always` in this scope
 --> src/main.rs:6:4
  |
6 |     #[serialize_always]
  |       ^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `sw-test`
```

This is extremely confusing if you never actually tried the non-array version of the code first, and just think you need to add a namespace qualification or enable a feature or something. If it's not supported on arrays that's odd but no big deal — it should definitely be documented though. (And of course if it is meant to be supported on arrays it's a bug.)

Using Rust 1.53, `Cargo.toml`:

```toml
[package]
name = "sw-test"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.9"
```
