### ISSUE TITLE
`DefaultOnError` falls back to default unexpectedly

### ISSUE THREAD

**Issue by Skgland** [jonasbb/serde_with#756]
Attempting to roundtrip a value fails for the `Bug` struct in the reduced example below while it works for `Working`, the only difference being the `DefaultOnError` on the `field` field in `Bug`.

I would have expected both tests to pass but only `test_working` does.

```rust,lib.rs
use serde_with::{serde_as, DefaultOnError};

#[derive(Debug, Default, serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq)]
#[repr(u8)]
pub enum Enum {
    #[default]
    A,
    B,
}

#[serde_as]
#[derive(Debug, Clone, serde::Deserialize, serde::Serialize, PartialEq, Eq)]
pub struct Bug {
    #[serde_as(as = "DefaultOnError")]
    #[serde(default)]
    pub field: Enum,
}


#[serde_as]
#[derive(Debug, Clone, serde::Deserialize, serde::Serialize, PartialEq, Eq)]
pub struct Working {
    #[serde(default)]
    pub field: Enum,
}

#[test]
fn test_bug() {
    let val = Bug{
        field: Enum::B,
    };
    let data = ron::to_string(&val).unwrap();
    let nval = ron::from_str(&data).unwrap();
    assert_eq!(val, nval)
}


#[test]
fn test_working() {
    let val = Working{
        field: Enum::B,
    };
    let data = ron::to_string(&val).unwrap();
    let nval = ron::from_str(&data).unwrap();
    assert_eq!(val, nval)
}

```

```toml,Cargo.toml
[package]
name = "serde_with_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "0.8.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_with = "3.8.1"
```
